# Docker Compose für Jimmy's Tapas Bar Website
# Einfache Installation auf Unraid mit docker-compose

version: '3.8'

services:
  jimmys-tapas-bar:
    build: .
    container_name: jimmys-tapas-bar
    image: jimmys-tapas-bar:latest
    ports:
      - "8080:80"  # Ändern Sie 8080 zu Ihrem gewünschten Port
    volumes:
      - ./:/usr/share/nginx/html:ro  # Website-Dateien als Read-Only einbinden
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin  # Zeitzone anpassen
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"  # Für Traefik Reverse Proxy (optional)
      - "traefik.http.routers.jimmys-tapas-bar.rule=Host(`jimmys-tapas-bar.local`)"
      - "traefik.http.services.jimmys-tapas-bar.loadbalancer.server.port=80"

# Optionale Netzwerke für erweiterte Setups
networks:
  default:
    name: jimmys-tapas-bar-network